/**
 * SETU — User Trust Engine (SIMULATED verification, frontend-only).
 *
 * Nothing here is backed by live staff checkpoints. Verification events are
 * generated by the demo simulator so the UI can visibly prove the maths.
 */

import { CrowdLevel, MAX_LEVEL } from "./decayWeightedEngine";

export const DEFAULT_TRUST_SCORE = 1.0;
export const MIN_TRUST_SCORE = 0.5;
export const MAX_TRUST_SCORE = 1.5;
export const LEARNING_RATE = 0.05;

export interface VerificationEvent {
  id: string;
  userId: string;
  reportedLevel: CrowdLevel;
  actualLevel: CrowdLevel;
  timestamp: number;
  error: number;
  previousScore: number;
  newScore: number;
}

export function clampTrust(score: number): number {
  return Math.min(MAX_TRUST_SCORE, Math.max(MIN_TRUST_SCORE, score));
}

export function verificationError(
  reportedLevel: CrowdLevel,
  actualLevel: CrowdLevel,
): number {
  return Math.abs(reportedLevel - actualLevel) / MAX_LEVEL;
}

/** Pure trust update: returns the new (clamped) score. */
export function nextTrustScore(
  currentScore: number,
  reportedLevel: CrowdLevel,
  actualLevel: CrowdLevel,
): number {
  const error = verificationError(reportedLevel, actualLevel);
  const accuracy = 1 - error;
  const target = MIN_TRUST_SCORE + accuracy * (MAX_TRUST_SCORE - MIN_TRUST_SCORE);
  return clampTrust(currentScore + LEARNING_RATE * (target - currentScore));
}

export function applyVerification(
  currentScore: number,
  userId: string,
  reportedLevel: CrowdLevel,
  actualLevel: CrowdLevel,
  timestamp: number = Date.now(),
): VerificationEvent {
  const newScore = nextTrustScore(currentScore, reportedLevel, actualLevel);
  return {
    id: `ver-${timestamp}-${Math.random().toString(36).slice(2, 7)}`,
    userId,
    reportedLevel,
    actualLevel,
    timestamp,
    error: verificationError(reportedLevel, actualLevel),
    previousScore: currentScore,
    newScore,
  };
}

export function trustTier(score: number): "Low" | "Neutral" | "Trusted" {
  if (score >= 1.15) return "Trusted";
  if (score <= 0.85) return "Low";
  return "Neutral";
}
